### ISSUE TITLE
[BUG] arc export does not work on samplearc_rnaseq

### ISSUE THREAD

**Issue by floWetzels** [nfdi4plants/arcCommander#109]
**Describe the bug**
I was unable build the arc.json on the RNA Sequencing Example ARC (https://gitlab.nfdi4plants.de/martinkuhl/samplearc_rnaseq). After running `arc export` from the root directory of the ARC I got the following output:
```
Start processing command with the arguments:
	Path:Field ""
 
Start Arc Export 
Done processing command.
```

After running `arc assay export -a Talinum_RNASeq_minimal -s TalinumFacultativeCAM` I got:
```
Start processing command with the arguments:
	AssayIdentifier:Field "Talinum_RNASeq_minimal"
	Path:Field ""
	StudyIdentifier:Field "TalinumFacultativeCAM"
 
Start Assay export 
Start exporting single assay 
ERROR: Assay file "/home/wetzels/arc/samplearc_rnaseq/assays/Talinum_RNASeq_minimal/isa.assay.xlsx" could not be read:
 System.NullReferenceException: Object reference not set to an instance of an object.
   at FSharpSpreadsheetML.Cell.includeSharedStringValue(SharedStringTable sharedStringTable, Cell cell)
   at FSharpSpreadsheetML.Row.mapCells@101.Invoke(Cell x)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
   at FSharpSpreadsheetML.Row.mapCells(FSharpFunc`2 f, Row row)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 77
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at <StartupCode$ISADotNet-XLSX>.$SparseTable.loop@88-4(FSharpList`1 labels, IEnumerator`1 en, String prefix, SparseTable matrix, FSharpList`1 remarks, Int32 lineNumber)
   at ISADotNet.XLSX.SparseTable.FromRows(IEnumerator`1 en, FSharpList`1 labels, Int32 lineNumber, FSharpOption`1 prefix)
   at ISADotNet.XLSX.Contacts.fromRows(FSharpOption`1 prefix, Int32 lineNumber, IEnumerator`1 rows)
   at ISADotNet.XLSX.AssayFile.MetaData.loop@29-11(IEnumerator`1 en, FSharpOption`1 lastLine, FSharpList`1 assays, FSharpList`1 contacts, Int32 lineNumber)
   at ISADotNet.XLSX.AssayFile.MetaData.fromRows(IEnumerable`1 rows)
   at ISADotNet.XLSX.AssayFile.Assay.fromSpreadsheet@91-4.Invoke(SheetData sheet)
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 53
   at ISADotNet.XLSX.AssayFile.Assay.fromSpreadsheet(SpreadsheetDocument doc)
   at ISADotNet.XLSX.AssayFile.Assay.fromFile(String path)
   at ArcCommander.APIs.AssayAPI.exportSingleAssay(ArcConfiguration arcConfiguration, FSharpMap`2 assayArgs) in /home/wetzels/arcCommander/src/ArcCommander/APIs/AssayAPI.fs:line 627 
{"people":[],"assays":[{"filename":"Talinum_RNASeq_minimal/isa.assay.xlsx","measurementType":{"annotationValue":"mRNA Sequencing","termSource":"NCIT","termAccession":"http://purl.obolibrary.org/obo/NCIT_C129432"},"technologyType":{"annotationValue":"Next Generation Sequencing","termSource":"NCIT","termAccession":"http://purl.obolibrary.org/obo/NCIT_C101293"},"technologyPlatform":"Illumina HiSeq 2500"}]} 
Done processing command.
```

This shows to problems: First, the arcCommander does not work on this example arc, and second, the verbosity of the output or error message differs between the full export and the assay export.

**To Reproduce**
See above.

**OS and framework information (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by HLWeil** [comment]
Thank you for bringing this up.
This took quite some time but I could identify the source of the problem. In the `Investigation` sheet of the `isa.assay.xlsx` file, there are empty cells in one line: 

```xml
<row r="14" spans="1:5" x14ac:dyDescent="0.2">
	<c r="A14" t="s">
		<v>29</v>
	</c>
	<c r="B14" s="11" t="s">
		<v>30</v>
	</c>
	<c r="D14" s="11"/>
	<c r="E14" s="11"/>
</row>
```
(see `D14` and `E14`)

This makes the function fail, which tries to obtain a value from this cell. This is perfectly fine `xlsx` but a problem on the `FSharpSpreadsheetML` and `ISADotNet` side. I will open an Issue there.

Also I will look into why the `verbosity` is so different between the two `command`s, which in principle call the same functions.

**Comment by HLWeil** [comment]
Hey @floWetzels,

could you try this again with the newest version `0.3.2` and check if the error persists?
