### ISSUE TITLE
[BUG] issue with SMB fileserver macOS

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#185]
This might be a very specific issue with the local (fileserver) setting. However, if other users run into a similar issue, it might make sense to collect here. 

## setup

- macOS Ventura 13.2
- arc version 0.4.0
- git version 2.39.0
- fileserver (NetApp grid) mounted via smb

## steps (removed file server address)

```bash
arcdir="/Volumes/<---fileserver--->/demoarc"
mkdir -p $arcdir; cd $arcdir
arc init
```

## error

```bash
Start processing command with the arguments:
        Branch:Field ""
        EditorPath:Field ""
        GitLFSByteThreshold:Field ""
        Owner:Field ""
        RepositoryAddress:Field ""
 
Start Arc Init 
Done processing command. 
ERROR: System.IO.IOException: Input/output error : '/Volumes/<---fileserver--->/demoarc/.arc/.gitkeep'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at ArcCommander.APIs.ArcAPI.init(ArcConfiguration arcConfiguration, FSharpMap`2 arcArgs)
   at ArcCommander.Program.handleCommand@215.Invoke(ArcConfiguration arcConfiguration, FSharpMap`2 arcArgs)
   at ArcCommander.Program.processCommand[a,T](ArcConfiguration arcConfiguration, FSharpFunc`2 commandF, ParseResults`1 r)
   at ArcCommander.Program.handleCommand(ArcConfiguration arcConfiguration, ArcCommand command)
   at ArcCommander.Program.main(String[] argv) Input/output error : '/Volumes/<---fileserver--->/demoarc/.arc/.gitkeep'
```

**Comment by Brilator** [comment]
Basically same steps via Linux, same file server, works: 

### Linux Setup

- Ubuntu 20.04.6 LTS
- arc v0.4.0
- git version 2.40.0
- Fileserver eingebunden per `sudo mount -t cifs -o ...


```bash
arcdir="/<---fileserver--->/demoarc/"
mkdir -p $arcdir; cd $arcdir
arc init
arc i create -i test
arc sync -f -r https://git.nfdi4plants.org/brilator/linuxtest/
```

**Comment by omaus** [comment]
Is `<---fileserver--->` a valid name? Because this looks suspicious to me. In Windows, you wouldn't be allowed to choose such a name.

**Comment by Brilator** [comment]
> Is <---fileserver---> a valid name? Because this looks suspicious to me. In Windows, you wouldn't be allowed to choose such a name.

:D No, it's not. That's what I meant by "(removed file server address)"

**Comment by Brilator** [comment]
```
2023-04-06 10:08:58.6559 ArcCommanderMainLog TRACE: Start ArcCommander
2023-04-06 10:08:58.7467 ProcessCommandLog INFO: Start processing command with the arguments:
	Branch:Field ""
	EditorPath:Field ""
	GitLFSByteThreshold:Field ""
	Owner:Field ""
	RepositoryAddress:Field ""

2023-04-06 10:08:58.7668 ProcessCommandLog TRACE: and the config:
	general.authclientid:80f4fbff13c3a27713860b6e71755fb3cba7adf644cf71a7cfcc9c1f67ac3680
	general.authredirecturi:http://localhost:7890
	general.authscope:openid email profile read_repository write_repository
	general.editor:nano
	general.forceeditor:false
	general.gitlfsbytethreshold:150000000
	general.gitlfsrules:**/dataset/**
	general.rootfolder:.arc
	general.verbosity:1
	general.workdir:/Volumes/............/demoarc
	assay.files:README.md
	assay.folders:dataset;protocols
	assay.rootfolder:assays
	study.files:README.md
	study.folders:protocols;resources
	study.rootfolder:studies
	isamodel.assay:folder.assay.rootfolder
	isamodel.assayfilename:isa.assay.xlsx
	isamodel.investigationfilename:isa.investigation.xlsx
	isamodel.studiesfilename:isa.studies.xlsx
	isamodel.studyfilename:isa.study.xlsx
	run.rootfolder:runs
	workflow.dockerfile:Dockerfile
	workflow.rootfolder:workflows

2023-04-06 10:08:58.7717 ArcInitLog INFO: Start Arc Init
2023-04-06 10:08:58.7723 ArcInitLog TRACE: Create Directory
2023-04-06 10:08:58.7723 ArcInitLog TRACE: Initiate folder structure
2023-04-06 10:08:58.7885 ProcessCommandLog INFO: Done processing command.
```

**Comment by omaus** [comment]
> > Is <---fileserver---> a valid name? Because this looks suspicious to me. In Windows, you wouldn't be allowed to choose such a name.
> 
> :D No, it's not. That's what I meant by "(removed file server address)"

Ha! Missed that one! 😅

---

Okay, according to the error message along with the log, the ArcCommander is not able to create a file in the directory.
We will have to investigate this further.

Does this error only occur on your server but _not_ when working on a local folder? If so, it might be a problem with permissions.

**Comment by Brilator** [comment]
only on that server and only when trying with mac not linux

**Comment by omaus** [comment]
Could you check if you have fewer permissions with your Mac account or when using the terminal from your Mac account?

**Comment by Brilator** [comment]
same university user login

**Comment by Brilator** [comment]
macOS Ventura 13.2
on the mac it is connected via the finder option

**Comment by Brilator** [comment]
This might actually be a server issue as I also keep running into issues with pure git
> fatal: .git/index: index file smaller than expected

**Comment by Brilator** [comment]
Yes, turned out to be an issue with the file server supporting only macOS ≤ 11.01..
