### ISSUE TITLE
[BUG] Adding assay performer fails and argument -s is irritating

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/arcCommander#214]
**Describe the bug**

When registering an assay performer, the argument -a is not recognized. 

```bash
arc a person register -s MY_STUDY -a MY_ASSAY -l LASTNAME -f FIRSTNAME
```
and
```bash
arc a person register-a MY_ASSAY -l LASTNAME -f FIRSTNAME
```
do not work: 

> ERROR: ERROR: unrecognized argument: '-a'.

When reading the help, it says --assayidentifier or -s. This is irritating. However I executed this as well.
```bash
arc a person register -s MY_ASSAY -l LASTNAME -f FIRSTNAME
```
Start processing command with the arguments:
	Address:Field ""
	Affiliation:Field ""
	AssayIdentifier:Field "MY_ASSAY"
	Email:Field ""
	Fax:Field ""
	FirstName:Field "FIRSTNAME"
	LastName:Field "LASTNAME"
	MidInitials:Field ""
	ORCID:Field ""
	Phone:Field ""
	Roles:Field ""
	RolesTermAccessionNumber:Field ""
	RolesTermSourceREF:Field ""

Start Person Register
Done processing command.
ERROR: System.Exception: Metadata sheetname Investigation could not be found System.Exception: Metadata sheetname Investigation could not be found
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at ArcCommander.APIs.AssayAPI.Contacts.register(ArcConfiguration arcConfiguration, FSharpMap`2 personArgs)
   at ArcCommander.Program.handleAssayContactsSubCommands@128-2.Invoke(ArcConfiguration arcConfiguration, FSharpMap`2 personArgs)
   at ArcCommander.Program.processCommand[a,T](ArcConfiguration arcConfiguration, FSharpFunc`2 commandF, ParseResults`1 r)
   at ArcCommander.Program.handleAssayContactsSubCommands(ArcConfiguration arcConfiguration, AssayPersonCommand contactsVerb)
   at ArcCommander.Program.handleAssaySubCommands(ArcConfiguration arcConfiguration, AssayCommand assayVerb)
   at ArcCommander.Program.handleCommand(ArcConfiguration arcConfiguration, ArcCommand command)
   at ArcCommander.Program.main(String[] argv)

Moreover, the assay performer fields in the isa.assay.xlsx file remain empty and nothing is added to the isa.investigation.xlsx file.

**Expected behavior**
arc a person register -a MY_ASSAY -l LASTNAME -f FIRSTNAME

with
--assayidentifier or -a to pass the assay identifier

and with the information being added to the isa.assay.xlsx file as well as to the isa.investigation.xlsx file.

**OS and framework information (please complete the following information):**
 - OS: macOS 
 - OS Version: Ventura 13.5.1
 - ARC Commander Version: v0.5.0

**Comment by HLWeil** [comment]
Ah okay I see, the short-hand flag is of course flat out wrong and needs to be updated. 

We're currently working on integrating the new back-end https://github.com/nfdi4plants/ARCtrl into the ArcCommander (It is also the back-end for the ARCitect). This should also fix many of the issues the ArcCommander has, as the ARCtrl is already well tested. 
Just as a heads-up.
