### ISSUE TITLE
[BUG] Handle Xlsx files edited in LibreOffice

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/arcCommander#87]
**Describe the bug**
After editing e.g. an `assay xlsx file` with `LibreOffice`, it can't be opened using the 'SpreadsheetDocument.Open' method from the 'DocumentFormat.OpenXml' library, which in turn is used in `ISADotNet.XLSX`. Therefore all `ArcCommander` commands working on xlsx files will fail when these were previously edited using LibreOffice.

Exact error message can be seen under `Additional context`

**Potential fix**

The problem could be fixed by first opening the `xlsx` as a `package` and fixing the the line in memory. `ISADotNet.XLSX` provides functionality to easily read the fixed `assay` or `investigation` file afterwards:

```fsharp
let s = System.IO.File.ReadAllBytes(fileName)
let stream = new System.IO.MemoryStream(s)

let wdPackage =  System.IO.Packaging.Package.Open(stream, FileMode.Open, FileAccess.ReadWrite)

let uri = new Uri("/xl/webextensions/taskpanes.xml", UriKind.Relative);

wdPackage.DeletePart(uri)
wdPackage.CreatePart(uri,contentType = "application/vnd.ms-office.webextensiontaskpanes+xml")

let document = DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(wdPackage)

ISADotNet.XLSX.AssayFile.Assay.fromSpreadsheet document
```

The file could then be written again by `ISADotNet.XLSX` functions, resulting in files that can be again used by the ArcCommander, Excel or LibreOffice

What remains as a question is how this behaviour is provided to the user. Should the ArcCommander automatically try to fix files it can't open or should there be user intervention required? 
Alternatively there could be a command dedicated to fix these corrupt files.

**Additional context**
Running 
```fsharp
DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(fileName,false)
```
results in 
```
DocumentFormat.OpenXml.Packaging.OpenXmlPackageException: The document cannot be opened because there is an invalid part with an unexpected content type. 
[Part Uri=/xl/webextensions/taskpanes.xml], 
[Content Type=application/xml], 
[Expected Content Type=application/vnd.ms-office.webextensiontaskpanes+xml].
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(String path, Boolean readWriteMode)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable)
   at <StartupCode$FSI_0021>.$FSI_0021.main@()
Stopped due to error
```

Same message will pop up when using `ISADotNet.XLSX.AssayFile.Assay.fromFile` or any ArcCommander command working on xlsx files

**Comment by omaus** [comment]
I really like your potential fix and propose it. 👍🏻 

Regarding
> What remains as a question is how this behaviour is provided to the user. Should the ArcCommander automatically try to fix files it can't open or should there be user intervention required?

I'd suggest to not bother the User with these things and let the AC instead do the magic in the background. Nevertheless, a warning should be printed.

Another question to me is if the AC should check for a LibreOffice-Xlsx when reading or trying to open it always with the standard method and doing the fix-solution in case of fail. For the former way we would need to find always-occuring specific identifiers for an Xlsx being created/edited by LibreOffice.

**Comment by HLWeil** [comment]
The `application` with which the `xlsx file` was created can be found in the `xlsx package` under `docProps/app.xml`:

E.g.: 
```
<Application>LibreOffice/7.2.4.1$Linux_X86_64 LibreOffice_project/20$Build-1</Application>
```
or 
```
<Application>Microsoft Excel</Application>
```

Files written using `ISADotNET.XLSX` currently don't contain this `docProps/app.xml` part. But I guess this should potentially be added to improve traceability over potential changes in both ISADotNET and the ArcCommander.
